{{- if not .Values.env.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crew-api-referenceimpl-v1.fullname" . }}
  labels:
{{ include "crew-api-referenceimpl-v1.labels.standard" . | indent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.env.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}