{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crew-api-referenceimpl-v1.fullname" . }}
  labels:
{{ include "crew-api-referenceimpl-v1.labels.standard" . | indent 4 }}
{{- end -}}